### ISSUE TITLE
Make it available to other Linux distros

### ISSUE THREAD

**Issue by LedBass** [alefnode/ubports-apps#14]
Hi guys

Hope this repo isn't dead

I've been using this app in my Nexus 4 with Ubuntu Touch for a while and it's responsiveness is just great!

And because of it's responsiveness I think it would be great to have it available in another distros via flatpak or snap so it can run in phones running Mobian, Manjaro ARM and etc.

If it suits better for the developers, it would be nice to have a README.md with the steps to compile and run this app

Congrats for the great work

**Comment by alefnode** [comment]
I though about it, i will tray to port to other distros, the problem now is that we are using code from Ubuntu.Components.ListItems, so i have to delete dependencies from ubports to align to all distros

**Comment by LedBass** [comment]
Nice, I don't know if helps, but devs from instagraph did it via snap

**Comment by Fuseteam** [comment]
fwiw considering this is basically webapp with a userscript, porting would mean, creating a webapp and injecting the userscript (if we are talking about whatsweb)

**Comment by alefnode** [comment]
I hear you!!

https://github.com/alefnode/mobile-whatsweb
https://build.opensuse.org/package/show/devel:ARM:Factory:Contrib:PinePhone/mobile-whatsweb
https://twitter.com/hadrianweb/status/1507362672446259205

**Comment by LedBass** [comment]
> I hear you!!
> 
> https://github.com/alefnode/mobile-whatsweb https://build.opensuse.org/package/show/devel:ARM:Factory:Contrib:PinePhone/mobile-whatsweb https://twitter.com/hadrianweb/status/1507362672446259205

I LOVE YOU, MAN!!!!! THANK YOU! =D
