### ISSUE TITLE
(WhatsWeb) Stickers can't be sent

### ISSUE THREAD

**Issue by nicolascolla** [alefnode/ubports-apps#15]
If you send any kind of sticker to any of your contacts, it will never be sent; it will appear as a gray double tick but it will never be read (since it never arrives to the person), while regular messages, emojis and gifs do.

Example screenshot:

![](https://i.imgur.com/fa2tr3j.png)

As you can see, while other messages have been read, stickers always appear as unread; the other person never sees them.

I think this might be related to another problem I have noticed. The "update available" banner is always present at the top of the message list:

![](https://i.imgur.com/X9iHtP0.png)

When the banner is clicked, it refreshes the page but it never disappears.

**Comment by nicolascolla** [comment]
I have contacted WhatsApp about this but the person at the other end of the support request is basically a human bot (repeating some synonim of "have you tried turning it off and on again" half a dozen times), so I have no idea if this is a problem with WhatsApp or just WhatsWeb.

**Comment by Fuseteam** [comment]
fwiw the heart of WhatsWeb is here: https://github.com/alefnode/ubports-apps/blob/master/whatsweb/app/ubuntutheme.js
Whatsapp does not officially support Whatsapp Web on mobile so WhatsWeb injects a userscript

**Comment by alefnode** [comment]
Tested, and seem to be a whatsapp problem, not from this app
