### ISSUE TITLE
(WhatsWeb) Voice messages can't be sent

### ISSUE THREAD

**Issue by nicolascolla** [alefnode/ubports-apps#17]
The WhatsWeb apparmor file lacks the permission "microphone":

```
{
    "policy_groups": [
         "webview",
         "networking",
         "audio",
         "video",
         "content_exchange",
         "content_exchange_source",
         "keep-display-on"
    ],
    "policy_version": 16.04
}
```

When you hit the mic button to send a voice message, a pop-up asking you to give access to the mic appears:

![](https://i.imgur.com/Co6Rchz.jpg)

However, it seems like this is not as simple as adding "microphone" to the apparmor permissions. If you do that, the same thing happens.

**Comment by alefnode** [comment]
I will check if last components has access to that devices, when i strart didn't work even with morph

**Comment by alefnode** [comment]
With this MR we fix this problem ad add permission to send voice messages

https://github.com/alefnode/ubports-apps/pull/28
