### ISSUE TITLE
(WhatsWeb) Panel to attach an image is not responsive

### ISSUE THREAD

**Issue by nicolascolla** [alefnode/ubports-apps#18]
When you send an image or a tenor GIF, the panel is not responsive:

![](https://i.imgur.com/BS51cfE.jpg)

This happens both when you have selected a tenor GIF or when you are attaching an image or a file (with their respective options).

**Comment by alefnode** [comment]
I was working in this issue --> https://github.com/alefnode/ubports-apps/pull/29

Next revision will have features that fix it
