### ISSUE TITLE
[Whatsweb] black screen after inital white with whatsapp logo with pinephone

### ISSUE THREAD

**Issue by hakanrolsson** [alefnode/ubports-apps#2]
When starting whatsweb on the pinephone after initial white with whatsapp logo the screen goes black.
WhatsWeb 0.1.5 installed from OpenStore.

**Comment by alefnode** [comment]
Mmm, interesting, not happen for me in N5 or Meizu

Can you send logs from app?

**Comment by hakanrolsson** [comment]
[000003.log](https://github.com/alefnode/ubports-apps/files/4471323/000003.log)

**Comment by alefnode** [comment]
If you wait a little bit on black screen it should runs well

Can you check it?
Meanwhile, I am gonna try to fix it

**Comment by hakanrolsson** [comment]
Thanks, stays on black screen for ever.

**Comment by alefnode** [comment]
Did you use uadblock?

**Comment by hakanrolsson** [comment]
Not that I know, just tested there on pinephone build #292. Still black screen.

**Comment by alefnode** [comment]
Is still happen if you upgrade or downgrade version of ubports?

I didn't have PinePhone yet, i bought it last week, so soon i can test it too.

**Comment by alefnode** [comment]
Can you open the app and take logfile on folder
/home/phablet/.cache/upstart/application-click-alefnode.whatsweb_whatsweb_0.1.6.log

Maybe with that i can work more on the error

**Comment by hakanrolsson** [comment]
[application-click-alefnode.whatsweb_whatsweb_0.1.6.log](https://github.com/alefnode/ubports-apps/files/4509353/application-click-alefnode.whatsweb_whatsweb_0.1.6.log)

**Comment by davidbe** [comment]
I saw you pushed a new version today. I tried it immediatly on my pinephone. I have similar errors that @hakanrolsson :

```
Using Wayland-EGL
WebEngine compiled with X11 support, however qpa backend is not xcb. This may fail.
Running on wayland. Qt WebEngine will disable usage of the GPU.
Note: you can set the QT_WEBENGINE_DISABLE_WAYLAND_WORKAROUND
environment variable before running this application, but this is 
not recommended since this usually causes applications to crash.
shm_open() failed: Permission denied
file:///opt/click.ubuntu.com/alefnode.whatsweb/0.1.7/app/Main.qml:66:21: Unable to assign QQuickAnchorLine to QQuickItem*
Using the 'xdg-shell-v6' shell integration
[10326:10377:0608/171859.283846:ERROR:nss_util.cc(83)] Failed to create /home/phablet/.pki/nssdb directory.
[10326:10375:0608/171859.336350:ERROR:zygote_host_impl_linux.cc(271)] Failed to adjust OOM score of renderer with pid 10389: Permission denied (13)
js: Uncaught TypeError: Cannot read property 'childNodes' of undefined
js: Uncaught TypeError: Cannot read property 'stack' of null
[PERFORMANCE]: Last frame took 76 ms to render.
js: Uncaught TypeError: Cannot read property 'childNodes' of undefined
js: Uncaught TypeError: Cannot read property 'stack' of null
js: Uncaught TypeError: Cannot read property 'childNodes' of undefined
js: Uncaught TypeError: Cannot read property 'childNodes' of undefined
js: Uncaught TypeError: Cannot read property 'childNodes' of undefined
```
Are there things I could check out?

**Comment by alefnode** [comment]
I think it's a problem with PinePhone and the way they use Wayland, today it came my Pinephone CE and i can test it on it to do correct changes

**Comment by FriendlyGecko** [comment]
I have found that rotating the phone between landscape and portrait helps it render while in landscape. Perhaps it is a scaling issue. When in landscape mode it sometimes doubles up side by side and there is a ton of screen flicker. I may try compiling and messing with it later.

**Comment by alefnode** [comment]
Is still happenning?

**Comment by alefnode** [comment]
closed due to inactivity
