### ISSUE TITLE
(WhatsWeb) New conversations can't be started

### ISSUE THREAD

**Issue by nicolascolla** [alefnode/ubports-apps#22]
When you try to start a new conversation with a contact using this button:

![](https://i.imgur.com/IEEsCTR.jpg)

You will see the list of your contacts but, after selecting one, the app will bounce back to your conversations menu instead of to a chat. That makes it impossible to start a new convo.

**Comment by Fuseteam** [comment]
the interface is made out of multiple panes, 2 of which is always visible. 
the userscript hides one of the two panes to make it responsive.
it like doesn't the userscript to make the convo pane visible

**Comment by alefnode** [comment]
I add support for starting new chat in last MR
I will update to new package in open-store soon
