### ISSUE TITLE
(WhatsWeb) Update available banner is always present

### ISSUE THREAD

**Issue by nicolascolla** [alefnode/ubports-apps#23]
This banner is always present at the top. Tapping on it makes the website reload but the banner is still there:

![](https://i.imgur.com/DGBSY2m.jpg)

**Comment by Fuseteam** [comment]
i think that's related to it not actually updating

**Comment by alefnode** [comment]
I made a new Merge https://github.com/alefnode/ubports-apps/issues/23

This hides the banner when you click anywhere on the screen, and it should stay that way until you restart the app

**Comment by Fuseteam** [comment]
I think you meant to link #28

**Comment by alefnode** [comment]
Correct

I am going to close this issue and push it to open-store the new package with this changes --> https://github.com/alefnode/ubports-apps/pull/28
