### ISSUE TITLE
Whatsapp web not working anymore.

### ISSUE THREAD

**Issue by pparent76** [alefnode/ubports-apps#34]
Hello,

I don't know if I'm the only on experiencing this problem, but since few days what's app web refuses to launch anymore. It stays stuck on first loading screen saying "end-to-end encrypted". I've uninstalled the app and reinstalled it without success. 

Regards.

**Comment by pparent76** [comment]
By any chance is there a way to delete/reset all the user data linked to the app?

**Comment by Vistaus** [comment]
Same here: the entire app is unusable now because it's stuck on the end-to-end security welcome screen. Both on my phone (Redmi 9 with Ubuntu Touch) as well as my mums (Pixel 3a with Ubuntu Touch). Reinstalling doesn't work, no does deleting the user data through UT Tweak Tool.

**Comment by pparent76** [comment]
I did a fully fresh install of Ubports with version 20.04, solved the problem.

**Comment by Vistaus** [comment]
That's impossible as this is not UT version specific. WA changed something on their end.

**Comment by pparent76** [comment]
Well that worked like 2 days ago on my phone, after reinstall.

I just check again, and there seems to be a layout issue. Cos I briefly see my conversations display; and then a page goes on top with writtent "WhatsApp Web" and explantions about linking devices. Do you have the same? 

Probably a very little trick to ajust withing css/js

**Comment by Vistaus** [comment]
Yes, that's what I (and you in the OP) was talking about. So again: 20.04 doesn't solve it as WA changed something and @alefnode needs to update the CSS/JS.

**Comment by pparent76** [comment]
![photo_2023-03-25_22-18-57](https://user-images.githubusercontent.com/12755774/227742529-f067701a-41ae-4e9c-8ef9-cef526982a8e.jpg)

Just for disambiguation, here is what I get, right now.

I agree with you, just that when I opened this bug report, the problem I encountered was completely different.

**Comment by Vistaus** [comment]
Maybe the issue lies with WA themselves after all as my mum also has the issue with WA Web on her iPad now… Although it does display a bit more on screen (the contact list), but as for actually working, not really.

**Comment by pparent76** [comment]
Well still probably this panel should be forced to be invisible with the add Css within the app. Probably not hard to do. I would try it if it were not for the cross-compilation that I have no energy to put myself into.

**Comment by pparent76** [comment]
If you type fast enough on the contact list at stratup, you can access a conversation.

**Comment by dosolly** [comment]
Same here. OP5t  16.04 RC 2023 W12/3

![screenshot20230327_145727273](https://user-images.githubusercontent.com/68632418/227946463-62fc80bd-d53a-4c32-a25e-1fc38b4baa34.png)

**Comment by Vistaus** [comment]
I wonder if WhatsApp has figured us out and that's why it's not working anymore? Because at the moment, I'm temporarily blocked in all apps, even the real official ones for “violating the terms of use”. I'm only using WA with one person I'm really close to and have never sent any messages that would violate the terms, so the only thing that I can think of is that WA somehow managed to figure out WhatsWeb was a violation, therefore rendering the app unusable and temporarily banning at least me.

**Comment by pparent76** [comment]
For me I have no such problem, I use whatsDesk as well, works fine. Even on ubports I can access chats and send message if I click fast enough on the contact before the other panel pops on top.

**Comment by Vistaus** [comment]
I'm unbanned now, but they really did ban me for an hour and I have no other explanation for it.

**Comment by mihaelmilea** [comment]
Looks like https://github.com/alefnode/ubports-apps/issues/35 is the same issue as the one described in the second part of this thread.

**Comment by alefnode** [comment]
Last pull request should solve this issue, let me know if the error still persists

**Comment by pparent76** [comment]
Great thank's so much it works again!
