### ISSUE TITLE
whatsweb loads into an empty chat panel with no nav button

### ISSUE THREAD

**Issue by YougoCodes** [alefnode/ubports-apps#35]
since this afternoon, when the app logs in, briefly the contacts panel is shown, but the app then switchs to the chat panel without any chat open,  just the 'wallpaper' and no navigation button to go to the contacts panel

quickly tapping the contacts panel as it is briefly shown opens the chat that was clicked, but then again has no nav button to go back.

also the window is wider than the screen.

i think something may have changed on the website, that is now messing with the responsiveness tweaks

**Comment by Vistaus** [comment]
Same here: the entire app is unusable now. Both on my phone (Redmi 9 with Ubuntu Touch) as well as my mums (Pixel 3a with Ubuntu Touch).

**Comment by mihaelmilea** [comment]
Same here. Thank you for helping us, we really, really need this app. Thanks again!

**Comment by alefnode** [comment]
Last pull request should solve this issue, let me know if the error still persists

**Comment by mihaelmilea** [comment]
A big thank you! Wow...

It works beautifully... The settings window is narrower than the width of the screen but it's still usable.

**Comment by Vistaus** [comment]
Thank you so much!
