### ISSUE TITLE
(WhatsWeb) Support for focal

### ISSUE THREAD

**Issue by invertedEcho** [alefnode/ubports-apps#37]
Would be very nice if we could get focal support.

**Comment by YougoCodes** [comment]
I installed the Xenial click on Focal and everything seems to work the same as on Xenial. Consider it tested ;-)
@alefnode could you please find the time to publish it in the Focal store?

Thank you for your work

**Comment by Vistaus** [comment]
It does work fine on Focal, although as of today, the JavaScript is unresponsive again.

**Comment by alefnode** [comment]
Working on it, almost done, i am testing new code

**Comment by alefnode** [comment]
Fixed https://github.com/alefnode/ubports-apps/commit/c13957fee85a3e01a73f0112a774e38a9ec34180
Updated un open-store for Ubports (To channel focal and xenial)
