### ISSUE TITLE
(WhatsWeb) Again in need adjustment according to the new website

### ISSUE THREAD

**Issue by mihaelmilea** [alefnode/ubports-apps#38]
Whatsapp changed again its format so we can't access / view chats upon startup...

Again we are thanking you for taking the time to help with a new version of the app that would accommodate the changes.

Thank you!

**Comment by CH2010-star** [comment]
Hi. I have the same problem!!! So it is no fun to use whatsweb. Please can you help us?
Thank you!!! 

Best regards, CH

**Comment by alefnode** [comment]
Working on it, almost done, i am testing new code

**Comment by alefnode** [comment]
Fixed https://github.com/alefnode/ubports-apps/commit/c13957fee85a3e01a73f0112a774e38a9ec34180
Updated un open-store for Ubports
