### ISSUE TITLE
Some problems with GUI from mobile

### ISSUE THREAD

**Issue by OV3R02** [alefnode/ubports-apps#40]
Hello, whatsweb on my phone met some problems, it's like the app was setted in desktop mode. 
The chat section was cutted half by right screen and left menu doesn't disappear automatically when I try to open a chat that in this case doesn't show messagges. So I can't see messages sent to me and can't write them.

I want to thank the developer/s of this project, I think it is very important for who want to switch to Linux mobile OS to have apps like this.

I linked some screenshot of the app.
Thanks in advance.

![f1d40559-4421-435a-90fb-b0430a787e37](https://github.com/alefnode/ubports-apps/assets/161864135/f5beb6d4-36b3-4c4a-8124-f98e5c278037)
![dc6112e5-0cae-481b-9747-73bd4f90123d](https://github.com/alefnode/ubports-apps/assets/161864135/a02b1fd2-bc21-4295-a42d-e58724de9b52)

**Comment by alefnode** [comment]
Which phone are you using?

**Comment by OV3R02** [comment]
Fairphone 4. But now it seems that the problem has resolved itself. The GUI is now scaled correctly for the screen. The only little issue I've noticed is that the settings and contact information windows when opened seem to be a little too narrow and don't fill the entire screen.

![contacts](https://github.com/user-attachments/assets/d82f293f-4595-4d32-9d02-05ac5192f1a3)
![settings](https://github.com/user-attachments/assets/a2b9175c-c1ff-4b25-a9bb-f6af0f14ca48)

**Comment by alefnode** [comment]
I just have a fix for contact info width, i am testing it, soon you will get some news

**Comment by alefnode** [comment]
i have some problems, maybe i have to do a function for language to make beter performance, because when i fix profile and settings, brokes attachement and contact info, i tried with some hardcore fixes but it is not enough i will try adding a function for lang es-ES and for en-EN, then i will try to maybe get help from communitty for new lang

**Comment by Fuseteam** [comment]
> because when i fix profile and settings, brokes attachement and contact info, 

Yes i was running into this before, i believe the section for attachment get hidden when you fix the profile and settings, those two seem to interfer
