### ISSUE TITLE
Whatsweb logs out every session

### ISSUE THREAD

**Issue by YougoCodes** [alefnode/ubports-apps#5]
Os: ubuntu touch 16.04/devel/2020-08-28 
Device: bq auquaris M10
Whatsweb version: 0.1.7

OS: Ubuntu touch 16.04/devel/2020-08-27/2
Device: OnePlus One (bacon)
Whatsweb version: 0.1.7

Problem: whatsapp changed something, and now whatsweb can't stay logged in between sessions. Qr login page shows every time whatsweb starts.

**Comment by j2g2rp** [comment]
I think that this isn't related to a whatsapp update but a morph update because it doesn't happens on stable channel.
What I don't know if it must be solved on morph side or on webapp side.

**Comment by YougoCodes** [comment]
It may have to do with a change in how cookies are to be handled by webapps. more webapps are affected, but not all.

From a comment by Danfro in Telegram:

> Danfro, [02.09.20 08:59]
> Some webapps do store cookies. It is not a general problem. It may depend on implementation? 
> WebEngineView allows to specify cookie handling in a profile.

**Comment by Danfro** [comment]
Just stumbled upon this issue in [morph browser](https://github.com/ubports/morph-browser/issues/347). That does confirm my guesses. The problem lies within a change in cookie storage. This morph issue is addressed for OTA 13. So this might be solved without the need to change apps soon.

**Comment by j2g2rp** [comment]
It is me or it is solved in last rc (85)?

**Comment by alefnode** [comment]
I check in last RC and seems to be solved

**Comment by YougoCodes** [comment]
Just updated my oneplus one to UT/devel 2020-04-09 and confirm problem solved
And updated my bqM10 to UT/devel 2020-09-02/2 and confirm problem solved

**Comment by Fuseteam** [comment]
@YougoCodes if the problem is solved feel free to close the issue :p
