### ISSUE TITLE
Whatsweb client refresh error on pinephone ub ports

### ISSUE THREAD

**Issue by froeb** [alefnode/ubports-apps#9]
The good news is that your whatsweb 0.1.9 seems to basically work on the pine phone now: i could finaly scan the qr code, see my status, see my chat, select another chat on pine phone ubport editon with the latest updates. 

However, the app is still unusable because at start, the screen will stay black for a long time, while after that start, the screen will turn on and off very fast so that you can hardly read what is on the screen, rendering  the app unusable.

**Comment by Fuseteam** [comment]
yes the screen sometimes turns black, this doesn't seem to be pinephone specific, if it just works most of the time

**Comment by froeb** [comment]
Well, I would not mind the screen turning black at the start if I knew it was temporary and after that, the app would work. The real program is that after that app start the app has this kind of fast blink Screen Problem so that you can hardly see the screen when using it.

**Comment by Fuseteam** [comment]
is that persistent? or those restarting the app solve it? and does it do the same in morph?

**Comment by alefnode** [comment]
Did still happen this issue?

**Comment by alefnode** [comment]
Try testing https://github.com/alefnode/mobile-whatsweb
